import { z } from "zod";
import type { ToolDefinition } from "../types.js";
import { getConnection } from "./sqlConnect.js";
import { sqlSchemaTool } from "./sqlSchema.js";

export const sqlSchemaExportTool: ToolDefinition = {
  name: "sql_schema_export",
  description: "Export database schema as Mermaid ER diagram, Markdown documentation, or JSON. Useful for documentation, code generation, and sharing.",
  args: {
    label: z.string().max(100).describe("Connection label (from sql_connect)"),
    format: z.enum(["mermaid", "markdown", "json"]).optional().describe("Export format. Default: mermaid"),
  },
  async execute(args: { label: string; format?: "mermaid" | "markdown" | "json" }) {
    const res = await sqlSchemaTool.execute({ label: args.label, includeRowCounts: true });
    const text = res.content?.[0]?.text || "{}";
    if (res.isError) return res;
    const data = JSON.parse(text);
    const format = args.format || "mermaid";

    if (format === "json") return res;

    if (format === "mermaid") {
      return { content: [{ type: "text", text: JSON.stringify({ database: args.label, format: "mermaid", diagram: data.mermaid }) }] };
    }

    if (format === "markdown") {
      let md = `# Database Schema: ${args.label}\n\n`;
      md += `**Type:** ${data.type}  \n`;
      md += `**Tables:** ${data.totalTables}  \n`;
      md += `**Total Rows:** ${data.totalRows.toLocaleString()}  \n\n`;
      md += "---\n\n";
      for (const table of data.tables) {
        md += `## ${table.name}\n\n`;
        md += `**Rows:** ${table.rowCount.toLocaleString()}  \n`;
        if (table.indexes.length > 0) md += `**Indexes:** ${table.indexes.join(", ")}  \n`;
        md += "\n| Column | Type | Nullable | Default | Key |\n";
        md += "|--------|------|----------|---------|-----|\n";
        for (const col of table.columns) {
          const key = col.pk ? "PK" : table.foreignKeys?.some((fk: any) => fk.column === col.name) ? "FK" : "";
          md += `| ${col.name} | ${col.type} | ${col.nullable ? "YES" : "NO"} | ${col.default || "—"} | ${key} |\n`;
        }
        md += "\n";
        if (table.foreignKeys?.length > 0) {
          md += "**Foreign Keys:**  \n";
          for (const fk of table.foreignKeys) {
            md += `- \`${fk.column}\` → \`${fk.refTable}.${fk.refColumn}\`\n`;
          }
          md += "\n";
        }
        md += "---\n\n";
      }
      md += `\n*Generated by BVP Browser MCP Server*\n`;
      return { content: [{ type: "text", text: JSON.stringify({ database: args.label, format: "markdown", markdown: md }) }] };
    }

    return res;
  },
};
